image: python:3.7-stretch

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - apt-get update
          - apt-get install -y python3 zip
          - pip3 install pika
          - pip3 install -e .
          - cd tests && jolt build all
    - step:
        caches:
          - pip
        script:
          - apt-get update
          - apt-get install -y python3 zip
          - pip3 install pika
          - pip3 install jolt
          - cd tests && jolt build all
