version: "3"
services:
  jolt:
    container_name: jolt_amqp_worker
    build:
      context: .
      dockerfile: Dockerfile.rabbitmq
    volumes:
      - jolt-cache:/tmp/jolt-cache
  amqp-service:
    image: docker.io/rabbitmq
    ports:
      - "5672:5672"
  nginx-service:
    image: docker.io/nginx
    volumes:
      - jolt-cache:/usr/share/nginx/html
    ports:
      - "80:80"
volumes:
  jolt-cache:
