version: "3"
services:
  jolt:
    container_name: jolt_amqp_worker
    build:
      context: .
      dockerfile: Dockerfile.jolt-rabbitmq
    volumes:
      - jolt-cache:/tmp/jolt-cache
  amqp-service:
    container_name: rabbitmq
    build:
      context: .
      dockerfile: Dockerfile.rabbitmq
    ports:
      - "5672:5672"
  ftp-service:
    image: fauria/vsftpd
    environment:
      - FTP_USER=jolt
      - FTP_PASS=secret
      - PASV_MIN_PORT=65000
      - PASV_MAX_PORT=65004
    volumes:
      - jolt-cache:/home/vsftpd
    ports:
      - "21:21"
      - "65000-65004:65000-65004"
volumes:
  jolt-cache:
