version: "3"
services:
  jolt:
    container_name: jolt_amqp_worker
    build:
      context: .
      dockerfile: Dockerfile.jolt-rabbitmq
    volumes:
      - jolt-cache:/tmp/jolt-cache
  amqp-service:
    container_name: rabbitmq
    build:
      context: .
      dockerfile: Dockerfile.rabbitmq
    ports:
      - "5672:5672"
  nginx-service:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - jolt-cache:/usr/share/nginx/html
    ports:
      - "80:80"
volumes:
  jolt-cache:
