apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    component: rabbitmq
  name: rabbitmq-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
        component: rabbitmq
    spec:
      containers:
      - image: rabbitmq
        name: rabbitmq
        ports:
        - containerPort: 5672
---
apiVersion: v1
kind: Service
metadata:
  labels:
    component: rabbitmq
  name: rabbitmq-service
spec:
  ports:
  - port: 5672
  selector:
    app: rabbitmq
    component: rabbitmq
  type: LoadBalancer
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    component: jolt
  name: jolt-controller
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: jolt
        component: jolt
    spec:
      containers:
      - image: joltreg.azurecr.io/jolt:v1-rabbitmq
        name: jolt
